### ISSUE TITLE
New team-mail.org Domains

### ISSUE THREAD

**Issue by ITs-cedced** [SoftCreatR/disposable-email-domains#4]
svcache.com
viemery.com
topyte.com
wowcg.com

**Comment by SoftCreatR** [comment]
Added svcache.com via 88aa079444b2c2a873f63e8d0f3460f71c76fb1b
Added viemery.com via 88aa079444b2c2a873f63e8d0f3460f71c76fb1b
Added topyte.com via 85c52dbdbbfd0d10e5cb511c319f6d8fe5d09c99
Added wowcg.com via 85c52dbdbbfd0d10e5cb511c319f6d8fe5d09c99
